language: elixir
otp_release:
  - 18.3
  - 19.2
elixir:
  - 1.3.4
  - 1.4.0
script:
  - MIX_ENV=test mix do compile --warnings-as-errors, coveralls.json
after_success:
  - bash <(curl -s https://codecov.io/bash)
after_script:
  - "MIX_ENV=docs mix do deps.get, inch.report"
